Belt/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include("apps.log_reg.urls", namespace = "log_reg")),
    url(r'^pokes/', include("apps.poke_app.urls", namespace = "poke_app")),
]

apps/poke_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^logout$', views.logout, name = "logout"),
    url(r'^poke$', views.poke, name = "poke"),
]

apps/poke_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import Count
from django.db import models
from ..log_reg.models import User

class PokeManager(models.Manager):
	def poke(self, postData):
		# print postData['poker_id'], postData['poked_id'], "*****************"
		poker = User.objects.get(id = postData['poker_id'])
		poked = User.objects.get(id = postData['poked_id'])
		self.create(poker = poker, poked = poked)
		# print self.all()
		
	def my_pokes(self, id):
		me = User.objects.get(id = id)
		all_pokes = self.filter(poked = me)
		count = all_pokes.values('poker').distinct().count()
		print count
		return count
	
	def who_poked_me(self, id):
		me = User.objects.get(id = id)
		others = []
		pokers = self.filter(poked = me).values('poker__alias').distinct()
		print pokers, "()()()()()()()()()()"
		for each in pokers:
			others.append(each)
		return others




class Poke(models.Model):
	poker=models.ForeignKey(User,related_name='user_poker',null=True)
	poked=models.ForeignKey(User,related_name='user_poked',null=True)
	created_at=models.DateField(auto_now_add=True)
	updated_at=models.DateField(auto_now=True)
	objects = PokeManager()
# Create your models here.

apps/poke_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from ..log_reg.models import User
from .models import *
from django.core.urlresolvers import reverse
from django.db.models import Count


def index(request):
    if not 'user_name' in request.session:
        messages.add_message(request, messages.INFO, "Must be logged in to view this page")
        return redirect('log_reg:index')
    id = request.session['user_id']
    me = User.objects.get(id = request.session['user_id'])
    others = User.objects.all().exclude(id = request.session['user_id'])
    my_pokes = Poke.objects.my_pokes(id)
    pokers = Poke.objects.who_poked_me(id)
    pok = []
    for each in pokers:
        pok.append(User.objects.get(alias = each['poker__alias']))
    print pok, "^^^^^^^^^^^^^^^^^^"
    final = []

    for each in pok:
        d = {}
        count = Poke.objects.filter(poker = each, poked = me).count()
        print count, "==============="
        d['name'] = each.alias
        d['count'] = count
        final.append(d)
        print final
    
    
    # pokers2 = User.objects.all().exclude(id = id)
    # print pokers2, "77777777777777777777"


    # pokers2 = Poke.objects.all().exclude(poker = me)
    # for each in pokers2:
    #     if each.poked == me:
    #         print "ura"
    # print len(pokers2), "(((((00000000000)))))))"




    # print request.session['user_id'], "*******&&&&&&&&"
    context = {
        'others':others,
        'my_pokes':my_pokes,
        'pokers':final
    }
    return render(request, "poke_app/index.html", context)

def logout(request):
    request.session.flush()
    return redirect('log_reg:index')

def poke(request):
    if request.method == 'POST':
        Poke.objects.poke(request.POST)
        return redirect('poke_app:index')

# Create your views here.

apps/poke_app/templates/poke_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pokes</title>
</head>
<body>
    <a href="{% url 'poke_app:logout' %}">Logout</a>
        <h1>Welcome, {{request.session.user_name}}</h1>
        {% if my_pokes > 0 %}
            <p>{{my_pokes}} people poked you!</p>
        {% endif %}
    <br>
    {% for each in pokers|dictsortreversed:'count' %}
        <p>{{each.name}} poked you {{each.count}} times</p>
    {% endfor %}
    <br>
    <h4>People you may want to poke:</h4>
    <table>
        <thead>
            <th>Name</th>
            <th>Alias</th>
            <th>Email Adress</th>
            <th>Poke History</th>
            <th>Action</th>
        </thead>
        {% for each in others %}
            <tr>
                <td>{{each.name}}</td>
                <td>{{each.alias}}</td>
                <td>{{each.email}}</td>
                <td>{{each.user_poked.count}} pokes</td>
                <td>
                    <form action="{% url 'poke_app:poke' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="poker_id" value="{{request.session.user_id}}">
                        <input type="hidden" name="poked_id" value="{{each.id}}">
                        <input type="submit" value="Poke!">
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>

</body>
</html>