Belt/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include("apps.log_reg.urls", namespace = "log_reg")),
    url(r'^pokes/', include("apps.poke_app.urls", namespace = "poke_app")),
]

apps/log_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^register$', views.register, name = "register"),
    url(r'^login$', views.login, name = "login"),
]

apps/log_reg/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt, re
from datetime import datetime

EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+.[^@\s]+$")


class UserManager(models.Manager):
    def validate_and_register(self, postData):
        errors = {}
        
        # Name Validation
        if not len(postData['name']):
            errors['name'] = "Name field can not be empty."
        elif len(postData['name']) < 3:
            errors['name'] = "Name too short."
        
        # Alias Validation
        if not len(postData['alias']):
            errors['alias'] = "Alias field can not be empty."
        elif len(postData['alias']) < 3:
            errors['alias'] = "Alias too short."
        elif self.filter(alias = postData['alias']):
            errors['alias'] = "Error! Alias already in use."
        
        # Email Validation
        if not len(postData['email']):
            errors['email'] = "Email field can not be empty."
        elif not re.match(EMAIL_REGEX, postData['email']):
            errors['email'] = "Invalid email! Please input the right format of an email like: user@mail.com"
        elif self.filter(email = postData['email']):
            errors['email'] = "Error! Email already in use."

        # Password Validation
        if not len(postData['password']):
            errors['password'] = "Password field can not be empty."
        elif len(postData['password']) < 8:
            errors['password'] = "Password too short. Input at least 8 characters"
        elif postData['password'] != postData['confirm_pass']:
            errors['confirm_pass'] = "Password not confirmed. Please pay more attention"
        
        # Birthday validation
        if not postData['birthday']:
            errors['birthday'] = "Birthday field can not be empty."
        else:
            now = datetime.today().date()
            birthday = datetime.strptime(postData['birthday'], "%Y-%m-%d").date()
            # print now - birthday, "$#$##$#$#$#$#$#$#()()()(_(_)(_+(+_()+_(+(+_"
            if birthday >= now:
                errors['birthday'] = "Birthday can not be earlier than the current day."

        # Return of the validation results for register method
        if len(errors):
            return (False, errors)
        else:
            password = postData['password'].encode()
            hashed = bcrypt.hashpw(password, bcrypt.gensalt())
            self.create(name = postData['name'], alias = postData['alias'], email = postData['email'], password = hashed, birthday = birthday)
            return (True, postData['name'])

    def validate_and_login(self, postData):
        errors_login = {}
        # Email Validation when Login
        if not len(postData['email']):
            errors_login['login_email_error'] = "Please provide an email."
        else:
            if not self.filter(email = postData['email']):
                errors_login['login_error'] = "Email or password wrong."
        
        if not len(errors_login):
            user = self.filter(email = postData['email'])
        # # Password Validation when Login
            if not len(postData['password']):
                errors_login['login_password_error'] = "Please provide password."
            else:
                password = postData['password'].encode()
                hashed = self.filter(email = postData['email'])[0].password.encode()
                if not bcrypt.checkpw(password, hashed):
                    errors_login['login_error'] = "Email or password wrong."

        
        # Return of the validation results for login method
        if len(errors_login):
            return (False, errors_login)
        else:
            return (True, self.filter(email = postData['email']))






class User(models.Model):
    name = models.CharField(max_length = 255)
    alias = models.CharField(max_length = 255)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    birthday = models.DateField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()
# Create your models here.

apps/log_reg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages

def index(request):
    print "##########************"
    return render(request, "log_reg/index.html")

def register(request):
    result = User.objects.validate_and_register(request.POST)
    if result[0] == False:
        context = {
            'result':result[1]
        }
        return render(request, "log_reg/index.html", context)
    if result[0] == True:
        context = {
            'name': result[1],
            'action': "successfully registered!"
        }
        return render(request, "log_reg/index.html", context)

def login(request):
    result = User.objects.validate_and_login(request.POST)
    if result[0] == False:
        context = {
            'result':result[1]
        }
        return render(request, "log_reg/index.html", context)
    if result[0] == True:
        request.session['user_name'] = result[1][0].name
        request.session['user_id'] = result[1][0].id
        return redirect('poke_app:index')

# Create your views here.

apps/log_reg/templates/log_reg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login and Register | Home</title>
    <style>
    #error{
        color: red;
    }
    #success{
        color: green;
    }
    </style>
</head>
<body>
    <h1>Login</h1>

    {% for message in messages %}
        <h3 id="error">{{message}}</h3>
    {% endfor %}

    <form action="{% url 'log_reg:login' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="email">Email:</label></td>
                <td><input type="text" name="email"></td>
                <td id="error">{{result.login_email_error}}</td>
            </tr>
            <tr>
                <td><label for="password">Password:</label></td>
                <td><input type="password" name="password"></td>
                <td id="error">{{result.login_password_error}}</td>
            </tr>
        </table>
        <br>
        <p id="error">{{result.login_error}}</p>
        <br>
        <input type="submit" value="Login">
    </form>
    <br>
    <h3 id="success">{{name}} {{action}}</h3>
    
    
    <h1>Registration</h1>
    <form action="{% url 'log_reg:register' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="name">Name:</label></td>
                <td><input type="text" name="name"></td>
                <td id="error">{{result.name}}</td>
            </tr>
            <tr>
                <td><label for="alias">Alias:</label></td>
                <td><input type="text" name="alias"></td>
                <td id="error">{{result.alias}}</td>
            </tr>
            <tr>
                <td><label for="email">Email:</label></td>
                <td><input type="email" name="email"></td>
                <td id="error">{{result.email}}</td>
            </tr>
            <tr>
                <td><label for="password">Password:</label></td>
                <td><input type="password" name="password"></td>
                <td id="error">{{result.password}}</td>
            </tr>
            <tr>
                <td><label for="confirm_pass">Confirm password:</label></td>
                <td><input type="password" name="confirm_pass"></td>
                <td id="error">{{result.confirm_pass}}</td>
            </tr>
            <tr>
                <td><label for="birthday">Date of Birth:</label></td>
                <td><input type="date" name="birthday"></td>
                <td id="error">{{result.birthday}}</td>
            </tr>
        </table>
        <br>
        <input type="submit" value="Register">
    </form>
    <br>
</body>
</html>